name: Cancel test ignoring all signals matrix
on:
  - workflow_dispatch
jobs:
  cancel-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stop: [true, false]
    steps:
      - uses: actions/checkout@v3
      - name: wait for signal
        run: |
          # This demo ignores everything relevant (except SIGKILL, which
          # is of course not ignore-able), so you can see the timing of
          # github's signals on cancel, and which ones will get delivered.
          if [ ${{ matrix.stop }} = 'true' ]; then
            exit 1;
          fi;
          exec python3 signaller.py SIGINT SIGQUIT SIGTERM SIGHUP SIGPIPE
      - if: always()
        run: |
          cat signaller.pid
          cat signaller.log
          ps -efH
