name: Cancel test ignoring all signals
on:
  - workflow_dispatch
jobs:
  cancel-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: wait for signal
        run: |
          # This demo ignores everything relevant (except SIGKILL, which
          # is of course not ignore-able), so you can see the timing of
          # github's signals on cancel, and which ones will get delivered.
          exec python3 signaller.py SIGINT SIGQUIT SIGTERM SIGHUP SIGPIPE
      - if: always()
        run: |
          cat signaller.pid
          cat signaller.log
          ps -efH
